### ISSUE TITLE
FireFox returns "DOMException: Modifications are not allowed for this document" on mouse drop events

### ISSUE THREAD

**Issue by ljwagerfield** [upload-io/uploader#10]
When drag-dropping a file using FireFox, the following error occurs on drop:

```
DOMException: Modifications are not allowed for this document
```

However, the upload succeeds (there are no visible issues -- only an error message in the dev console).

**Comment by XshubhamX** [comment]
Hi @ljwagerfield, can i work on this?

**Comment by ljwagerfield** [comment]
Fixed by https://github.com/upload-io/uploader/commit/f2dae45c4f45c99eb8b284f2453cfb08f0143c04
