### ISSUE TITLE
Struggling to build from sources

### ISSUE THREAD

**Issue by jvlad** [upload-io/uploader#15]
I'm trying to run `npm run start:dev` within `./examples` dir. 
If I'm trying it right away, unsurprisingly it doesn't work and fails with the error `sh: webpack: command not found`. So I'm trying to run `npm install` first.

However, I see that scripts section of the `package.json` in the `examples` dir depends on `npm pack` script in the `./lib` dir. In particular, I mean this line:  https://github.com/upload-js/uploader/blob/ede4d75854971d1761cef244fc96558ff8224c0a/examples/package.json#L11 

---

When I'm navigating to `./lib` and trying to run `npm install` there, it fails with the following stack trace ending:  

```
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/binding/src/binding.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (...uploader/lib/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/17.4.0/bin/node" ".../uploader/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd ...uploader/lib/node_modules/node-sass
npm ERR! gyp ERR! node -v v17.4.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! Build failed with error code: 1
```

Apparently at least part of a problem is that `"sass-loader": "10.1.0"` is incompatible with my Node.js version `17.4.0`.

Changing 2 lines in https://github.com/upload-js/uploader/blob/f49be2bf1a4de769d5ddd23176917d01be0deb5c/lib/package.json

to  

``` json
"node-sass": "7.0.1",
"sass-loader": "12.6.0",
```

solved the issue of running `npm install` in `./lib` dir. But I'm not sure if the library stays functional after that. There are also some vulnerabilities discovered: `13 vulnerabilities (8 moderate, 5 high)`.

In general, having "Build from source" instructions in the `Readme` that mention the steps along with the dev environment prerequisites (like Node.js version) would help a lot.

**Comment by ljwagerfield** [comment]
Thank you for the detailed feedback @jvlad — I'll take a look this morning.

**Comment by ljwagerfield** [comment]
Closing, but please re-open if you feel I've missed anything!
