### ISSUE TITLE
Cannot drag crop targets with touch

### ISSUE THREAD

**Issue by kincaidoneil** [upload-io/uploader#22]
On a mobile device with touch gestures, the crop targets won't fluidly move when trying to drag them:

https://user-images.githubusercontent.com/6435238/231855208-30f46b92-34b5-4025-b0c9-51a3aedaaacc.mp4

**Comment by ljwagerfield** [comment]
Taking a look now (will hopefully resolve in the next few hours or so).

If you have any initial ideas, please feel free to share!

I appreciate this part of the code is a little in the weeds.

**Comment by ljwagerfield** [comment]
Fixed in 3.18.0.

Please shout if you have any further issues 👍

**Comment by kincaidoneil** [comment]
@ljwagerfield Thank you for incredible response time on these! 🙌
